name: PureEntitiesX
main: revivalpmmp\pureentities\PureEntities
version: "1.1"
api: ["2.1.0"]

load: STARTUP
authors: ["milk0417", "RevivalPMMP"]
description: Implement all MCPE entities
website: https://github.com/RevivalPMMP/PureEntitiesX
